### ISSUE TITLE
Create Terraform Config for the NGINX Instances

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/infra#512]

**Comment by Bouncey** [comment]
What do you need the config to do? Just a basic nginx setup serving from the default html directory? Or are you still using them as an API Gateway?

**Comment by raisedadead** [comment]
Sorry – The issue title is a bit of a misnomer.

These issues are just internal checklists for me & one of our cloud partners (Linode). I am currently porting over [the current config](https://github.com/freeCodeCamp/nginx-config).

We have used Terraform and Ansible to provision the NGINX instances.
