### ISSUE TITLE
Create Terraform Config the Teleport Cluster for Access Control

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/infra#513]

**Comment by Bouncey** [comment]
This is a HA terraform config I have used for inspiration in other places, although it is for AWS: https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ha-autoscale-cluster/README.md

**Comment by raisedadead** [comment]
Thanks – I did look at it. Hows is your take on Teleport? I have not used them much. For most intent and purposes, Cloudflare's Tunnel and Zero-Trust Gateway have been enough for us.

**Comment by Bouncey** [comment]
We use it for Kubernetes access, either Kubernetes API access for clients outside of a private VPC, or for accessing internal applications hosted in Kubernetes, like environment specific instances of ArgoCD.

For API access, Jenkins uses Machine-Id. And developers use `tsh login` to authenticate and `tsh kube login` to gain access to the Kubernetes cluster.

The docs are good, but they do assume some prior knowledge of how Teleport works internally.

They do have a relentless version upgrade lifecycle, which is easy to fall behind on for a self hosted Teleport cluster. If you can afford it, spring for a hosted cluster.

**Comment by raisedadead** [comment]
We have decided to go with Tailscale for now. The have generously onboarded us on their Open source Plan which should suffice our requirements in the short term
